---
mysql_mysqld_bind_address: '0.0.0.0'

mysql_databases:
- name: "{{ app_name }}"
  state: 'present'

# ---- MySQL server configuration ----
# Use this hash variable to set additional mysqld options
mysql_mysqld_options: {
  # INNODB
  'key_buffer': '16M',
  'innodb_buffer_pool_size': '64M',
  # In order to change this, you have to first shutdown, 
  # then move away the log files (ib_logfile0, ib_logfile1, and so on), 
  # then restart mysql.
  #'innodb_log_file_size = '32M'
  'innodb_file_per_table': '1',
  'innodb_flush_method': 'O_DIRECT',
  # OTHER
  'tmp_table_size': '8M',
  'max_heap_table_size': '32M',
  'query_cache_type': '0',
  'query_cache_size': '00',
  'max_connections': '50',
  'thread_cache_size': '10',
  'table_open_cache': '80',
  'open_files_limit': '65535',
}
